export class AppError extends Error {
  constructor(
    public code: string,
    message: string,
    public statusCode: number = 500,
    public details?: unknown
  ) {
    super(message);
    this.name = "AppError";
  }
}

export const ErrorCodes = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  VIRUS_DETECTED: "VIRUS_DETECTED",
  APPROVAL_PENDING: "APPROVAL_PENDING",
  ALREADY_APPROVED: "ALREADY_APPROVED",
  DOCUMENT_ARCHIVED: "DOCUMENT_ARCHIVED",
  INVALID_TOKEN: "INVALID_TOKEN",
  MFA_REQUIRED: "MFA_REQUIRED",
  STORAGE_QUOTA_EXCEEDED: "STORAGE_QUOTA_EXCEEDED",
  PASSWORD_PROTECTED: "PASSWORD_PROTECTED",
  APPROVAL_CHAIN_BLOCKED: "APPROVAL_CHAIN_BLOCKED",
} as const;
